### ISSUE TITLE
能不能专门开发一下对PDF中二维码的识别功能？

### ISSUE THREAD

**Issue by huxuyf** [xuncv/PDFium-aardio#4]
在一些发票（加油发票）的PDF文件中专门有一个二维码（一般在左上角），可以通过扫描识别二维码获知发票里的一些基本信息（比如发票代码，发票号码，开票日期，校验码，金额等）。虽然也可以通过识别PDF中的文本块来获取，但不同的PDF文件可能同样的信息位置不一样，这样就需要不断的调整位置，而二维码获取的信息比较准确。

所以不知道能不能针对PDF中的二维码专门做一个识别的功能？

**Comment by xuncv** [comment]
可将pdf转图片，然后使用aardio扩展库中的zbar库识别二维码
